server {
    listen 8443 ssl;
    server_name collxct.com.ng;

    ssl_certificate     /etc/letsencrypt/live/collxct.com.ng/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/collxct.com.ng/privkey.pem;

    client_max_body_size 5m;

    location / {
        proxy_pass http://recbot:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}
